spring:
  datasource:
    url: jdbc:h2:mem:testdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
#    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin